### ISSUE TITLE
Migrate attachments

### ISSUE THREAD

**Issue by Javier-Rotelli** [MichaelBelgium/mybb_to_flarum#21]
pretty much self explanatory. I don't know flarum's structure, but mybb's easy enough. 
I can work on this. if I can I'll try to make a PR somewhere during this weekend.

**Comment by MichaelBelgium** [comment]
But Flarum doesn't support attachments out of the box right? This is the same principle like private messages. Gotta chose an extension for it and check if the forum has it installed

**Comment by Javier-Rotelli** [comment]
well then, that makes it a little harder, 
but I figure we can create two modules:
1) imports data from mybb and returns it in some standard format
2)takes that data, and inserts it into a specific extension. 
we can start by adding compatibility to https://extiverse.com/extension/fof/upload since it's the most used. and leave the door open for future integrations.

what do you think?

**Comment by online0227** [comment]
I would love to see in Flarum. Also I saw Discourse did this for importing mybb with attachements at https://gist.github.com/rahilwazir/a8399eeb3c499bded8873f2892369cac

**Comment by MichaelBelgium** [comment]
I've taken a look to fof/upload but it seems thats more like a "global upload" system and not per discussion? As mybb does have attachments linked to threads/posts. If i use fof/upload the mybb attachments would randomly be on the file system without any links to it
