### ISSUE TITLE
Trouble to import avatars

### ISSUE THREAD

**Issue by redfish462** [MichaelBelgium/mybb_to_flarum#25]
Hi, 

Thank you for the script ! It worked well (apart 2/3 things). 

I used this command : ./flarum migrate-data:from-mybb --host=127.0.0.1 --user=user--password='password' --db=mybb --path=/mybb/path/Upload

I had theses logs : 

```9 user groups migrated
9653 users migrated
24 categories migrated
PHP Notice:  Undefined offset: 0 in /flarum/vendor/s9e/text-formatter/src/Plugins/BBCodes/Parser.php on line 247
4583 discussions migrated
112824 posts migrated
Migration successful``` 


But : Avatars are not imported (on web ui it works well but the script is crashing after 30 seconds so I used the command line)

**Comment by MichaelBelgium** [comment]
I'll have look at avatars and that php notice, it's been some time i've tested the avatars. I don't think MyBB changed something about avatar paths right?

**Comment by MichaelBelgium** [comment]
Ive pushed an update (v8.1) that rewrites some stuff of the command, 

* flarums avatar folder has been changed 
* path option can just be `/mybb`
