### ISSUE TITLE
Error: Class "mysqli" not found

### ISSUE THREAD

**Issue by toreador34** [MichaelBelgium/mybb_to_flarum#26]
Hi,

when i try migraiton, it shows "Oops! Something went wrong. Please reload the page and try again" error message. I inspect logs and saw this error message

flarum.ERROR: Error: Class "mysqli" not found in /var/www/vendor/michaelbelgium/mybb-to-flarum/src/Migrator.php:45

**Comment by MichaelBelgium** [comment]
You need to have the php mysqli extension installed and loaded

**Comment by toreador34** [comment]
Thank you for your quick response.

I did install and enable mysqli but it shows different error now

flarum.ERROR: Error: mysqli object is already closed in /var/www/vendor/michaelbelgium/mybb-to-flarum/src/Migrator.php:46

**Comment by toreador34** [comment]
php-fpm dockerfile

FROM php:8.0.2-fpm-alpine
RUN apk add libjpeg-turbo-dev libpng-dev freetype-dev
RUN docker-php-ext-configure gd --with-freetype=/usr/include/ --with-jpeg=/usr/include/ \
    && docker-php-ext-install -j$(nproc) gd pdo_mysql pdo mysqli

**Comment by MichaelBelgium** [comment]
That error must mean the connection isn't working aka wrong password, db, username or host
