### ISSUE TITLE
Doesn't work with newest version

### ISSUE THREAD

**Issue by waifunerd** [MichaelBelgium/mybb_to_flarum#7]
It doesn't appear to work with the newest release of Flarum. (reminder to fix)

**Comment by Syltan-Adam** [comment]
It did specify that it was for 1.0Beta6.

**Comment by MichaelBelgium** [comment]
Was planning to check if it still works anyway. Can't find DB changes in the full changelog tho

_Sent from my Bq Aquaris M5 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by MichaelBelgium** [comment]
@waifunerd I just tested it with beta 7 and it still works for me ...
