### ISSUE TITLE
Passwords not working

### ISSUE THREAD

**Issue by GIVENALITY** [MichaelBelgium/mybb_to_flarum#9]
Hello,

I used the migrator and successfully moved posts as well as categories and users. However the passwords are not working from mybb. I cannot login even on the admin account.

**Comment by MichaelBelgium** [comment]
As in the README:

> Users (their passwords are ALL reset to a bcrypt hash from current time)

Mybb and Flarum don't use the same hashing method for passwords, so this means all passwords are reset.

**Comment by GIVENALITY** [comment]
> As in the README:
> 
> > Users (their passwords are ALL reset to a bcrypt hash from current time)
> 
> Mybb and Flarum don't use the same hashing method for passwords, so this means all passwords are reset.

Understood. So what are the users to do?

**Comment by MichaelBelgium** [comment]
They all need to request a new password by clicking "forget password" in the login dialog

**Comment by GIVENALITY** [comment]
Okay. Hopefully this migration will be easier in future.

**Comment by MichaelBelgium** [comment]
Well unfortunately there's no other way for now. The passwords will be reset nonetheless, unless MyBB changes their hashing/encrypting methodology - or flarum does. But I doubt. Mybb is using md5 which is quite old and insecure
